CREATE TABLE USER (
    USER_KEY VARCHAR(50) PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255), -- 패스워드 해시 (선택적)
    OAUTH_PROVIDER VARCHAR(20), -- OAuth 공급자 (예: 'facebook', 'google')
    OAUTH_ID VARCHAR(100), -- OAuth ID
    MDFY_ID VARCHAR(50),
    MDFY_DTM DATETIME,
    REG_ID VARCHAR(50),
    REG_DTM DATETIME
);

CREATE TABLE OAUTH_TOKEN (
    TOKEN_ID VARCHAR(255) PRIMARY KEY,
    USER_KEY VARCHAR(50),
    ACCESS_TOKEN VARCHAR(255), -- 액세스 토큰
    REFRESH_TOKEN VARCHAR(255), -- 리프레시 토큰
    EXPIRE_DTM DATETIME, -- 토큰 만료 시간
    MDFY_ID VARCHAR(50),
    MDFY_DTM DATETIME,
    REG_ID VARCHAR(50),
    REG_DTM DATETIME
);


CREATE TABLE CHATROOM (
    CHATROOM_KEY VARCHAR(50) PRIMARY KEY,
    CREATE_USER_KEY VARCHAR(50),
    MDFY_ID VARCHAR(50),
    MDFY_DTM DATETIME,
    REG_ID VARCHAR(50),
    REG_DTM DATETIME
);


CREATE TABLE CHATROOM_USER_MAPPING (
    CHATROOM_KEY VARCHAR(50) PRIMARY KEY,
    USER_KEY VARCHAR(50),
    ENTER_SEQ INT,
    ENTER_DTM DATETIME,
    LEAVE_YN VARCHAR(1),
    LEAVE_DTM DATETIME,
    MDFY_ID VARCHAR(50),
    MDFY_DTM DATETIME,
    REG_ID VARCHAR(50),
    REG_DTM DATETIME
);


CREATE TABLE MESSAGE(
    MESSAGE_SEQ BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    CHATROOM_KEY VARCHAR(50),
    SEND_USER_KEY VARCHAR(50),
    SEND_DTM DATETIME,
    MDFY_ID VARCHAR(50),
    MDFY_DTM DATETIME,
    REG_ID VARCHAR(50),
    REG_DTM DATETIME
);
