
-- USERS table: stores user information including credentials and profile details
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '사용자 ID',
    USERNAME VARCHAR(50) NOT NULL UNIQUE COMMENT '사용자 이름',
    EMAIL VARCHAR(100) NOT NULL UNIQUE COMMENT '이메일',
    PASSWORD_HASH VARCHAR(255) NOT NULL COMMENT '암호 해시',
    OAUTH_PROVIDER VARCHAR(50) COMMENT 'OAuth 제공자',
    OAUTH_ID VARCHAR(100) COMMENT 'OAuth ID',
    GENDER ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL COMMENT '성별',
    BIRTHDATE DATE NOT NULL COMMENT '생년월일',
    BIO TEXT COMMENT '자기소개',
    PROFILE_PICTURE_URL VARCHAR(255) COMMENT '프로필 사진 URL',
    MDFY_ID VARCHAR(50) NULL COMMENT '수정자',
    MDFY_DTM DATETIME NULL COMMENT '수정일자',
    REG_ID VARCHAR(50) NULL COMMENT '등록자',
    REG_DTM DATETIME NULL COMMENT '등록일자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자'
);

-- USER_PREFERENCES table: stores user preferences for matching criteria
CREATE TABLE USER_PREFERENCES (
    USER_ID INT PRIMARY KEY COMMENT '사용자 ID',
    PREFERRED_GENDER ENUM('MALE', 'FEMALE', 'OTHER', 'ANY') DEFAULT 'ANY' COMMENT '선호 성별',
    AGE_RANGE_START INT DEFAULT 18 COMMENT '선호 나이 범위 시작',
    AGE_RANGE_END INT DEFAULT 100 COMMENT '선호 나이 범위 끝',
    MDFY_ID VARCHAR(50) NULL COMMENT '수정자',
    MDFY_DTM DATETIME NULL COMMENT '수정일자',
    REG_ID VARCHAR(50) NULL COMMENT '등록자',
    REG_DTM DATETIME NULL COMMENT '등록일자'
);

-- MATCHES table: records matched users
CREATE TABLE MATCHES (
    MATCH_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '매칭 ID',
    USER_ID_1 INT NOT NULL COMMENT '첫 번째 사용자 ID',
    USER_ID_2 INT NOT NULL COMMENT '두 번째 사용자 ID',
    MATCHED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '매칭일자',
    MDFY_ID VARCHAR(50) NULL COMMENT '수정자',
    MDFY_DTM DATETIME NULL COMMENT '수정일자',
    REG_ID VARCHAR(50) NULL COMMENT '등록자',
    REG_DTM DATETIME NULL COMMENT '등록일자',
    UNIQUE(USER_ID_1, USER_ID_2)
);

-- MESSAGES table: stores messages exchanged between matched users
CREATE TABLE MESSAGES (
    MESSAGE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '메시지 ID',
    MATCH_ID INT NOT NULL COMMENT '매칭 ID',
    SENDER_ID INT NOT NULL COMMENT '발신자 ID',
    MESSAGE_TEXT TEXT NOT NULL COMMENT '메시지 내용',
    SENT_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '발신일자',
    MDFY_ID VARCHAR(50) NULL COMMENT '수정자',
    MDFY_DTM DATETIME NULL COMMENT '수정일자',
    REG_ID VARCHAR(50) NULL COMMENT '등록자',
    REG_DTM DATETIME NULL COMMENT '등록일자'
);

-- LIKES table: records user likes
CREATE TABLE LIKES (
    LIKE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '좋아요 ID',
    USER_ID INT NOT NULL COMMENT '사용자 ID',
    LIKED_USER_ID INT NOT NULL COMMENT '좋아요한 사용자 ID',
    LIKED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '좋아요한 시간',
    MDFY_ID VARCHAR(50) NULL COMMENT '수정자',
    MDFY_DTM DATETIME NULL COMMENT '수정일자',
    REG_ID VARCHAR(50) NULL COMMENT '등록자',
    REG_DTM DATETIME NULL COMMENT '등록일자',
    UNIQUE(USER_ID, LIKED_USER_ID)
);

-- DISLIKES table: records user dislikes
CREATE TABLE DISLIKES (
    DISLIKE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '싫어요 ID',
    USER_ID INT NOT NULL COMMENT '사용자 ID',
    DISLIKED_USER_ID INT NOT NULL COMMENT '싫어요한 사용자 ID',
    DISLIKED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '싫어요한 시간',
    MDFY_ID VARCHAR(50) NULL COMMENT '수정자',
    MDFY_DTM DATETIME NULL COMMENT '수정일자',
    REG_ID VARCHAR(50) NULL COMMENT '등록자',
    REG_DTM DATETIME NULL COMMENT '등록일자',
    UNIQUE(USER_ID, DISLIKED_USER_ID)
);
